lane(:snappy) do |options|
  snapshot(
    project: 'Example.xcodeproj',
    scheme: 'ExampleUITests',
    devices: ['iPhone X', 'iPhone SE', "iPhone Xʀ", "iPhone XS"],
    languages: ['ca', 'fr', 'zh', 'de'],
    result_bundle: true,
    output_simulator_logs: true,
    clear_previous_screenshots: true,
    localize_simulator: true,
    verbose: true,
  )
end
